# This file contains the default train settings
device: 'cuda:0' # or 'cpu'

# Model
variant: 'F0' # F0 - F7
num_classes: 1000     # Number of classes 
stochdepth_rate: 0.25 # 0-1, the probability that a layer is dropped during one step
alpha: 0.2            # Scaling factor at the end of each block
se_ratio: 0.5         # Squeeze-Excite expansion ratio
groups: 128           # Number of groups in convolution

# Dataset
dataset: '/media/benjs/ext/'  # Dataset root directory
num_workers: 8                # Number of workers in dataloader

# Training
batch_size: 60        # Batch size
epochs: 5000          # Number of epochs
learning_rate: 0.1    # Learning rate
scale_lr: True        # Scale learning rate with batch size. lr = lr*batch_size/256
momentum: 0.9
weight_decay: 0.00002 # 
nesterov: True
clipping: 0.1
